# What is NumPy?

# NumPy is the fundamental package for scientific computing in Python

## Key Points


### NumPy stands for NUmerical PYthon

### Mainly used for numerical computations

### It is iterable

### It is mutable

# Why NumPy arrays over lists and tuples?

Vectorization

Vectorization means performing operations on entire arrays at once instead of using loops.

NumPy performs operations much faster, especially on large datasets
Uses less memory

Homogeneous:NumPy arrays store data more efficiently because they use a fixed data type.

### Creating Arrays
### Homogeneous data:same data type
### Vectorization: means performing operations on entire arrays at once instead of using loops.
### Dimensions in NumPy

In [21]:
import time
import numpy as np
print("Running slow Python list...")
# start = time.time()
np_result = np.arange(30_000_000) * 2
np_result
# py_result=[]

# for i in range(30_000_000):   # 30 million entries
#     py_result.append(i * 2)

# # print("Python finished in:", time.time() - start, "seconds")

# py_result


Running slow Python list...


array([       0,        2,        4, ..., 59999994, 59999996, 59999998])

In [22]:
import numpy as np

print("\n1. CREATING ARRAYS")
# 1D array
a = np.array([1, 2, 3])
print("a =", a)
# 2D array
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
print("\nb =\n", b)
# 3D array
c = np.array([[(1.5,2,3), (4,5,6)],
              [(3,2,1), (4,5,6)]], dtype=float)
print("\nc =\n", c)
# functions
print("\nnp.zeros((3,4)) =\n", np.zeros((3,4)))
print("\nnp.ones((2,3,4)) =\n", np.ones((2,3,4), dtype=np.int16))
print("\nnp.arange(10,25,5) =", np.arange(10,25,5))
print("\nnp.linspace(0,2,9) =", np.linspace(0,2,9))

print("\nnp.full((2,2),7) =\n", np.full((2,2),7))
print("\nnp.eye(2) =\n", np.eye(2))
print("\nnp.random.random((2,2)) =\n", np.random.random((2,2)))
print("\nnp.empty((3,2)) =\n", np.empty((3,2)))
print("seed",np.random.seed(2))



1. CREATING ARRAYS
a = [1 2 3]

b =
 [[1.5 2.  3. ]
 [4.  5.  6. ]]

c =
 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]

np.zeros((3,4)) =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.ones((2,3,4)) =
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

np.arange(10,25,5) = [10 15 20]

np.linspace(0,2,9) = [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

np.full((2,2),7) =
 [[7 7]
 [7 7]]

np.eye(2) =
 [[1. 0.]
 [0. 1.]]

np.random.random((2,2)) =
 [[0.52611271 0.55979773]
 [0.54034107 0.71391382]]

np.empty((3,2)) =
 [[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]
seed None


### Copying Arrays

In [24]:
c.ndim


3

In [25]:
import numpy as np

a = np.array([1,2,3])

print("2. COPYING ARRAYS")

h = a.view()
print("View of a:", h)

deep_copy = a.copy()
print("Deep copy of a:", deep_copy)


2. COPYING ARRAYS
View of a: [1 2 3]
Deep copy of a: [1 2 3]


### Indexing & Slicing

In [27]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)
c = np.array([[(1.5,2,3),(4,5,6)],
              [(3,2,1),(4,5,6)]], dtype=float)

print("3. INDEXING & SLICING")

print("a[2] =", a[2])
print("b[1,2] =", b[1,2])
print("a[0:2] =", a[0:2])

print("Reversed a:", a[::-1])

print("a[a < 2] =", a[a<2])

print("b[[1,0,1,0],[0,1,2,0]] =", b[[1,0,1,0],[0,1,2,0]])




3. INDEXING & SLICING
a[2] = 3
b[1,2] = 6.0
a[0:2] = [1 2]
Reversed a: [3 2 1]
a[a < 2] = [1]
b[[1,0,1,0],[0,1,2,0]] = [4.  2.  6.  1.5]


In [28]:
a = np.array([1, 2, 3, 4, 5])

print(a[1:4])   # [2, 3, 4]
print(a[:3])    # [1, 2, 3]
print(a[3:])    # [4, 5]
print(a[-2:])   # last 2 → [4, 5]
print(a[::-1])  # reverse → [5, 4, 3, 2, 1]

[2 3 4]
[1 2 3]
[4 5]
[4 5]
[5 4 3 2 1]


In [29]:
# slicing
test = np.array([[1,2,3],[4,5,6]])

print(test[0,0])    # 1
print(test[:,1])   # [2,5]
print(test[1,:])    # [4,5,6]


1
[2 5]
[4 5 6]


### Sorting

In [31]:
import numpy as np

print("4. SORTING ARRAYS")

unsorted = np.array([3,1,2])
unsorted.sort()
print("Sorted array:", unsorted)


4. SORTING ARRAYS
Sorted array: [1 2 3]


### Inspecting Arrays

In [33]:
import numpy as np

a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)

print("5. INSPECTING ARRAYS")

print("Shape of a:", a.shape)
print("Length of a:", len(a))
print("Dimensions of b:", b.ndim)
print("Size of b:", a.size)
print("Size of b:", b.size)
print("dtype of b:", b.dtype)
print("dtype name:", b.dtype.name)
print("b as int:\n", b.astype(int))

5. INSPECTING ARRAYS
Shape of a: (3,)
Length of a: 3
Dimensions of b: 2
Size of b: 3
Size of b: 6
dtype of b: float64
dtype name: float64
b as int:
 [[1 2 3]
 [4 5 6]]


### Array Mathematics

In [35]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print("6. ARRAY MATH")

print("a + b =\n", np.add(a,b))
print("a - b =\n", np.subtract(a,b))
print("a * b =\n", np.multiply(a,b))
print("a / b =\n", np.divide(a,b))

print("\nElement-wise sin(a):\n", np.sin(a))
print("Element-wise sqrt(b):\n", np.sqrt(b))
print("Dot product:\n", a.dot(b.T))

6. ARRAY MATH
a + b =
 [[ 2  4  6]
 [ 8 10 12]]
a - b =
 [[0 0 0]
 [0 0 0]]
a * b =
 [[ 1  4  9]
 [16 25 36]]
a / b =
 [[1. 1. 1.]
 [1. 1. 1.]]

Element-wise sin(a):
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
Element-wise sqrt(b):
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Dot product:
 [[14 32]
 [32 77]]


### Comparison

In [37]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print("7. COMPARISON")

print("a == b:\n", a==b)
print("a < 2:\n", a<2)
print("Array equal:", np.array_equal(a,b))


7. COMPARISON
a == b:
 [[ True  True  True]
 [ True  True  True]]
a < 2:
 [[ True False False]
 [False False False]]
Array equal: True


### Aggregates

In [39]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print("8. AGGREGATES")

print("Sum:", a.sum())
print("Min:", a.min())
print("Max (axis=0):", b.max(axis=0))
print("Cumulative sum (axis=1):\n", b.cumsum(axis=1))
print("Mean:", a.mean())
print("Median:", np.median(b))
print("Std dev:", np.std(b))


8. AGGREGATES
Sum: 21
Min: 1
Max (axis=0): [4 5 6]
Cumulative sum (axis=1):
 [[ 1  3  6]
 [ 4  9 15]]
Mean: 3.5
Median: 3.5
Std dev: 1.707825127659933


In [40]:
import numpy as np

py_list = [1, 2, 3, 4]
np_array = np.array(py_list)
np_array

array([1, 2, 3, 4])

In [41]:
np_array.tolist()
np_array

array([1, 2, 3, 4])

In [43]:
import time

print("Running slow Python list...")
# start = time.time()
np_result = np.arange(30_000_000) * 2
np_result

# for i in range(30_000_000):   # 30 million entries
#     py_result.append(i * 2)

# # print("Python finished in:", time.time() - start, "seconds")

# py_result


Running slow Python list...


array([       0,        2,        4, ..., 59999994, 59999996, 59999998])