In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [34]:
cleaned_data=pd.read_csv(r"C:\Users\ahmed\Revision\workshop\Py_for_ML\Workshop_lessons\dataset\cleaned_data\final_df.csv")
cleaned_data


Unnamed: 0  Bedrooms  Bathrooms  HouseSize_sqft  Neighborhood  Condition  \
0             0         5          3            1999             3          1   
1             1         5          2            1745             3          0   
2             2         5          3            1810             0          2   
3             3         6          4            2409             0          0   
4             4         3          2            1706             2          0   
..          ...       ...        ...             ...           ...        ...   
374         374         4          2            1612             3          0   
375         375         3          2            1115             0          1   
376         376         6          3            2342             2          1   
377         377         4          1            1810             3          1   
378         378         4          3            2295             3          2   

            Price  
0    1.223983e+06  
1    1.125837e+06  
2    1.078208e+06  
3    1.240305e+06  
4    9.781016e+05  
..            ...  
374  1.012177e+06  
375  6.313032e+05  
376  1.315946e+06  
377  1.046926e+06  
378  1.360911e+06  

[379 rows x 7 columns]

In [70]:
df=cleaned_data.drop(["Unnamed: 0","Neighborhood","Condition"],axis=1)
df

Bedrooms  Bathrooms  HouseSize_sqft         Price
0           5          3            1999  1.223983e+06
1           5          2            1745  1.125837e+06
2           5          3            1810  1.078208e+06
3           6          4            2409  1.240305e+06
4           3          2            1706  9.781016e+05
..        ...        ...             ...           ...
374         4          2            1612  1.012177e+06
375         3          2            1115  6.313032e+05
376         6          3            2342  1.315946e+06
377         4          1            1810  1.046926e+06
378         4          3            2295  1.360911e+06

[379 rows x 4 columns]

In [37]:
X=df.drop("Price",axis=1)

y=df["Price"]
y.shape

(379,)

In [38]:
X

Bedrooms  Bathrooms  HouseSize_sqft
0           5          3            1999
1           5          2            1745
2           5          3            1810
3           6          4            2409
4           3          2            1706
..        ...        ...             ...
374         4          2            1612
375         3          2            1115
376         6          3            2342
377         4          1            1810
378         4          3            2295

[379 rows x 3 columns]

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)


In [71]:
print("X_train shape",X_train.shape,"\n y_train shape",y_train.shape)
print("")
print("X_test shape",X_test.shape,"\n y_test shape",y_test.shape)
print()

X_train shape (303, 3) 
 y_train shape (303,)

X_test shape (76, 3) 
 y_test shape (76,)



## fit and transform the train data and transform the test and new data

# Algorithm that needs scaling Numeric values are
## 1-Linear Models 2- Distance Based Models.
### Linear models
  #### Linear Regression, Logistic Regression
### Distance Based Models
#### K-nearest Neighbours,Support Vector Machine(SVM),
### K-Means(unsupervised learning), PCA(Unsupervised learning)

### 1. Select numeric columns

### 2. Import and create a StandardSc

In [41]:
# Import and create a StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


In [42]:
X_train.shape

(303, 3)

### 3. Fit ONLY on training data

In [43]:
scaler.fit(X_train)

StandardScaler()

### 4. Transform train and test sets

In [44]:
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[num_cols] = scaler.transform(X_train)
X_test_scaled[num_cols] = scaler.transform(X_test)


In [45]:
print("X_train shape",X_train_scaled.shape,"\n y_train shape",y_train.shape)
print("")
print("X_test shape",y_test.shape,"\n y_test shape",y_test.shape)
print()

X_train shape (303, 3) 
 y_train shape (303,)

X_test shape (76,) 
 y_test shape (76,)



In [46]:
X_train_scaled


Bedrooms  Bathrooms  HouseSize_sqft
137 -0.607066  -0.341861       -1.774226
101 -0.607066  -0.341861       -0.179902
202  1.370793  -0.341861        0.837927
198 -0.607066   2.348630        1.251679
224 -0.607066  -1.687107       -0.731571
..        ...        ...             ...
71  -2.584925  -1.687107       -2.891355
106 -1.595995  -1.687107       -2.119019
270 -0.607066  -0.341861       -2.154877
348  0.381864  -0.341861        0.247641
102  0.381864  -1.687107        0.446242

[303 rows x 3 columns]

In [65]:
X_test_scaled

Bedrooms  Bathrooms  HouseSize_sqft
288  1.370793  -1.687107        0.672426
283  0.381864   2.348630        0.895852
327  0.381864  -0.341861       -0.519179
145  0.381864   1.003385        0.026974
55  -0.607066  -1.687107       -0.342645
..        ...        ...             ...
249 -0.607066  -0.341861       -1.131531
182  0.381864   1.003385        0.945502
317  0.381864  -0.341861        1.075145
110 -0.607066  -0.341861       -0.213002
332  0.381864   1.003385       -0.235069

[76 rows x 3 columns]

### 5 Build Model

In [49]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train)


LinearRegression()

### 6. Predict

In [72]:
y_predict = model.predict(X_test_scaled)
y_predict

array([440216.69414421, 477754.23993885, 440216.69414421, 440216.69414421,
       440216.69414421, 440216.69414421, 440216.69414421, 440216.69414421,
       477754.23993885, 440216.69414421, 440216.69414421, 440216.69414421,
       440216.69414421, 440216.69414421, 440216.69414421, 440216.69414421,
       452034.44188091, 440216.69414421, 440216.69414421, 440216.69414421,
       440216.69414421, 440216.69414421, 440216.69414421, 440216.69414421,
       440216.69414421, 440216.69414421, 440216.69414421, 440216.69414421,
       440216.69414421, 440216.69414421, 440216.69414421, 440216.69414421,
       440216.69414421, 440216.69414421, 440216.69414421, 440216.69414421,
       440216.69414421, 440216.69414421, 440216.69414421, 440216.69414421,
       440216.69414421, 440216.69414421, 440216.69414421, 440216.69414421,
       440216.69414421, 440216.69414421, 440216.69414421, 440216.69414421,
       452034.44188091, 440216.69414421, 440216.69414421, 440216.69414421,
       440216.69414421, 4

### 7. Evaluate the model (MSE, RMSE, R²)

In [51]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

mse = mean_squared_error(y_test, y_predict)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("RMSE:", rmse)
print("R² Score:", r2)


MSE: 7820259686.197807
RMSE: 88432.23216790249
R² Score: 0.8113758712288119


In [67]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=42)
model.fit(X_train_scaled, y_train)
y_predict= model.predict(X_test)
y_predict

array([1089390.89898737, 1158811.0044682 ,  984606.57846183,
       1014698.25150976,  846758.67747954, 1041383.70535962,
       1031287.09800885,  842877.13861435, 1437696.88778146,
       1041748.35343999, 1168196.4732086 ,  654301.35472646,
        850371.25943211,  918386.34581199, 1146781.29186567,
       1034226.30485312, 1073439.13809055,  759372.1831545 ,
        940084.96656129, 1003761.60033172, 1045855.50230831,
        655399.4745039 ,  943923.68103207, 1052021.33445512,
        682199.98141567,  805991.5396217 , 1099226.01842973,
        952978.63729167,  944892.80979135, 1113174.42621833,
        861042.48476184, 1113174.42621833,  821093.86870255,
        694599.95828571, 1097333.11483594, 1060324.86415304,
       1104166.86537272,  679129.17450002, 1025168.38666899,
       1030346.12026461,  918799.38343551,  815197.82858923,
        872296.30461648,  966930.32534219, 1034226.30485312,
        901683.52654104, 1008063.76910109, 1007347.28918938,
       1383535.20470088,

In [ ]:
# test=y_test-y_predict
# test
# t=pd.DataFrame(y_test,columns=[])

In [68]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

#  Calculate MSE (Mean Squared Error)
mse = mean_squared_error(y_test, y_predict)

#  Calculate RMSE (Root Mean Squared Error)
rmse = np.sqrt(mse)

#  Calculate R² Score
r2 = r2_score(y_test, y_predict)

#  Print results
print("MSE:", mse)
print("RMSE:", rmse)
print("R² Score:", r2)


MSE: 8679363187.575506
RMSE: 93163.09992467782
R² Score: 0.7906543535332233


In [ ]:
# Multiple Regression model

In [ ]:
# # ==========================
# # 📦 Import Libraries
# # ==========================
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import mean_squared_error, r2_score
# from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
# from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
# from sklearn.tree import DecisionTreeRegressor
# from sklearn.neighbors import KNeighborsRegressor
# from sklearn.svm import SVR
# import numpy as np

# # ==========================
# # 🧠 Define Regression Models
# # ==========================
# models = {
#     "Linear Regression": LinearRegression(),
#     "Ridge Regression": Ridge(alpha=1.0),
#     "Lasso Regression": Lasso(alpha=0.01),
#     "ElasticNet Regression": ElasticNet(alpha=0.01, l1_ratio=0.5),
#     "Decision Tree Regressor": DecisionTreeRegressor(random_state=42),
#     "Random Forest Regressor": RandomForestRegressor(n_estimators=100, random_state=42),
#     "Gradient Boosting Regressor": GradientBoostingRegressor(random_state=42),
#     "AdaBoost Regressor": AdaBoostRegressor(random_state=42),
#     "Support Vector Regressor": SVR(kernel='rbf'),
#     "K-Nearest Neighbors Regressor": KNeighborsRegressor(n_neighbors=5)
# }

# # ==========================
# # 📈 Train, Predict, and Print Results for Each Model
# # ==========================
# for name, model in models.items():
#     print("="*70)
#     print(f"🔹 Model: {name}")
#     print(model)
#     print("-"*70)
    
#     # Train model
#     model.fit(X_train, y_train)
    
#     # Predict
#     y_pred = model.predict(X_test)
    
#     # Evaluate metrics
#     mse = mean_squared_error(y_test, y_pred)
#     rmse = np.sqrt(mse)
#     r2 = r2_score(y_test, y_pred)
    
#     # Print results
#     print(f"MSE:  {mse:.4f}")
#     print(f"RMSE: {rmse:.4f}")
#     print(f"R² Score: {r2:.4f}")



# print("✅ All models have been evaluated successfully!")
# print('model =', name, ', r2 =', r2)





### Comparing the actual price with predicted data

In [52]:
import pandas as pd

# Create comparison DataFrame
comparison_df = pd.DataFrame({
    "Actual Price": y_test.values, #pandas series
    "Predicted Price": y_pred, #numpy
})
# errors=y_test-y_predict
# Add difference column
comparison_df["Difference"] = comparison_df["Actual Price"] - comparison_df["Predicted Price"]

comparison_df.head()


Actual Price  Predicted Price     Difference
0  1.088002e+06     1.098261e+06  -10258.606712
1  1.004517e+06     1.182462e+06 -177944.999900
2  8.434546e+05     9.281856e+05  -84730.974642
3  1.178394e+06     1.031720e+06  146673.036931
4  9.007468e+05     9.109380e+05  -10191.201184

#### Predicting New data

In [55]:
new_house = pd.DataFrame([{
    "Bedrooms": 3,
    "Bathrooms": 2,
    "HouseSize_sqft": 1500,
}])


### Scale the new data

In [ ]:
new_data_scaled = scaler.transform(new_data[num_cols])
new_pred = model.predict(new_data_scaled)


In [62]:
new_scaled = scaler.transform(new_house)
# Step 2: Convert back to DataFrame 
new_scaled_df = pd.DataFrame(new_scaled, columns=new_house.columns)
new_scaled_df

Bedrooms  Bathrooms  HouseSize_sqft
0 -0.607066  -0.341861       -0.828113

In [63]:
prediction = model.predict(new_scaled_df)
prediction

array([863574.17830352])

### Comparing Test Prediction With the Actual

In [33]:
import pandas as pd

# Create comparison DataFrame
comparison_df = pd.DataFrame({
    "Actual Price": y_test.values, #pandas series
    "Predicted Price": y_pred, #numpy
})
# errors=y_test-y_predict
# Add difference column
comparison_df["Difference"] = comparison_df["Actual Price"] - comparison_df["Predicted Price"]

comparison_df["Actual Price"] = comparison_df["Actual Price"].apply(lambda x: f"{x:,.0f}")
comparison_df["Predicted Price"] = comparison_df["Predicted Price"].apply(lambda x: f"{x:,.0f}")
comparison_df["Difference"] = comparison_df["Difference"].apply(lambda x: f"{x:,.0f}")

comparison_df.head()
# # test_data["y_predction"]=prediction
# # test_data
# # prediction

Actual Price Predicted Price Difference
0    1,088,002       1,100,216    -12,214
1    1,004,517       1,240,807   -236,291
2      843,455         856,832    -13,377
3    1,178,394       1,095,869     82,524
4      900,747         927,154    -26,407

In [64]:
import joblib
joblib.dump(model, "model.pkl")

['model.pkl']

In [66]:
joblib.dump(scaler, "scaler.pkl")


['scaler.pkl']