In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
cleaned_data=pd.read_csv(r"C:\Users\ahmed\AIBootCamp\Workshop_lessons\dataset\cleaned_data\final_df.csv")
cleaned_data


Unnamed: 0  Bedrooms  Bathrooms  HouseSize_sqft  Neighborhood  Condition  \
0             0         5          3            1999             3          1   
1             1         5          2            1745             3          0   
2             2         5          3            1810             0          2   
3             3         6          4            2409             0          0   
4             4         3          2            1706             2          0   
..          ...       ...        ...             ...           ...        ...   
374         374         4          2            1612             3          0   
375         375         3          2            1115             0          1   
376         376         6          3            2342             2          1   
377         377         4          1            1810             3          1   
378         378         4          3            2295             3          2   

            Price  
0    1.223983e+06  
1    1.125837e+06  
2    1.078208e+06  
3    1.240305e+06  
4    9.781016e+05  
..            ...  
374  1.012177e+06  
375  6.313032e+05  
376  1.315946e+06  
377  1.046926e+06  
378  1.360911e+06  

[379 rows x 7 columns]

remove Unnamed: 0,Neighborhood,Condition: they are nt important features
removing Neighborhood and Condition is optional but removing Unnamed: 0 is must 

Unnamed: 0 is not a real feature. It is:

An index column that got saved into the CSV by mistake

Created when you saved a DataFrame:
with out setting "index=False".
Pandas treats the old index as a normal column and names it Unnamed: 0.

In [3]:
df=cleaned_data.drop(["Unnamed: 0","Neighborhood","Condition"],axis=1)

df

Bedrooms  Bathrooms  HouseSize_sqft         Price
0           5          3            1999  1.223983e+06
1           5          2            1745  1.125837e+06
2           5          3            1810  1.078208e+06
3           6          4            2409  1.240305e+06
4           3          2            1706  9.781016e+05
..        ...        ...             ...           ...
374         4          2            1612  1.012177e+06
375         3          2            1115  6.313032e+05
376         6          3            2342  1.315946e+06
377         4          1            1810  1.046926e+06
378         4          3            2295  1.360911e+06

[379 rows x 4 columns]

# Split dataset into features (X) and target (y)
# X contains all input features except the target column "Price"
# y contains the target variable we want the model to predict


In [4]:
X=df.drop("Price",axis=1)

y=df["Price"]
y.shape

(379,)

In [5]:
X

Bedrooms  Bathrooms  HouseSize_sqft
0           5          3            1999
1           5          2            1745
2           5          3            1810
3           6          4            2409
4           3          2            1706
..        ...        ...             ...
374         4          2            1612
375         3          2            1115
376         6          3            2342
377         4          1            1810
378         4          3            2295

[379 rows x 3 columns]

# Train-Test Split:
# The dataset is divided into two parts:
# - Training set: used to train (teach) the machine learning model.
# - Testing set: used to evaluate how well the model performs on unseen data.
# This helps us check if the model can generalize(predict new, unseen data) and not just memorize the train data.


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# Train on 80% of the data
# Test on 20% of the data


In [7]:
print("X_train shape",X_train.shape,"\n y_train shape",y_train.shape)
print("")
print("X_test shape",X_test.shape,"\n y_test shape",y_test.shape)
print()

X_train shape (303, 3) 
 y_train shape (303,)

X_test shape (76, 3) 
 y_test shape (76,)



## fit and transform the train data and transform the test and new data

# Algorithm that needs scaling Numeric values are
## 1-Linear Models 2- Distance Based Models.
### Linear models
  #### Linear Regression, Logistic Regression
### Distance Based Models
#### K-nearest Neighbours,Support Vector Machine(SVM),
### K-Means(unsupervised learning), PCA(Unsupervised learning)

### 1. Select numeric columns

### 2. Import and create a StandardScaler

In [8]:
# Import and create a StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


In [9]:
X_train.shape

(303, 3)

### 3. Fit ONLY on training data

In [10]:
scaler.fit(X_train)

StandardScaler()

### 4. Transform train and test sets

In [11]:
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [12]:
print("X_train shape",X_train_scaled.shape,"\n y_train shape",y_train.shape)
print("")
print("X_test shape",y_test.shape,"\n y_test shape",y_test.shape)
print()

X_train shape (303, 3) 
 y_train shape (303,)

X_test shape (76,) 
 y_test shape (76,)



In [13]:
X_train_scaled


array([[-0.60706565, -0.34186114, -1.7742257 ],
       [-0.60706565, -0.34186114, -0.17990235],
       [ 1.37079339, -0.34186114,  0.83792692],
       [-0.60706565,  2.34863041,  1.25167865],
       [-0.60706565, -1.68710691, -0.73157133],
       [ 0.38186387,  1.00338464,  0.5483007 ],
       [-0.60706565,  1.00338464,  0.02697352],
       [ 0.38186387,  1.00338464,  0.10144883],
       [ 2.35972291,  1.00338464,  2.36604999],
       [ 0.38186387, -0.34186114,  0.28625794],
       [-0.60706565, -0.34186114, -1.00188913],
       [-2.58492468, -1.68710691, -0.71226291],
       [ 0.38186387, -0.34186114,  1.05859451],
       [ 0.38186387,  1.00338464,  0.59795091],
       [-1.59599516, -0.34186114, -0.90534706],
       [-0.60706565, -1.68710691, -1.71078377],
       [-0.60706565, -0.34186114,  0.94550237],
       [-1.59599516, -0.34186114, -1.59769163],
       [ 1.37079339, -0.34186114,  1.06135285],
       [ 0.38186387,  1.00338464,  0.91240223],
       [-0.60706565, -0.34186114, -0.902

In [14]:
X_test_scaled

array([[ 1.37079339, -1.68710691,  0.67242622],
       [ 0.38186387,  2.34863041,  0.89585216],
       [ 0.38186387, -0.34186114, -0.51917877],
       [ 0.38186387,  1.00338464,  0.02697352],
       [-0.60706565, -1.68710691, -0.3426447 ],
       [ 0.38186387, -0.34186114,  0.32487477],
       [-0.60706565,  1.00338464,  0.35521656],
       [-1.59599516, -1.68710691, -0.55503726],
       [ 1.37079339,  2.34863041,  2.06814874],
       [ 0.38186387,  1.00338464,  0.32211642],
       [ 1.37079339, -0.34186114,  0.96205244],
       [-1.59599516, -1.68710691, -1.77974239],
       [-0.60706565, -0.34186114, -1.34668224],
       [-0.60706565, -0.34186114, -0.36195311],
       [-0.60706565,  1.00338464,  1.04756113],
       [ 0.38186387, -0.34186114,  0.02697352],
       [ 2.35972291,  1.00338464,  0.02697352],
       [-1.59599516, -0.34186114, -1.288757  ],
       [ 0.38186387, -0.34186114, -0.35643642],
       [ 0.38186387, -0.34186114,  0.06559035],
       [ 0.38186387, -0.34186114,  0.346

### 5 Build Model- we will use Linear Regression and randomforest regressor.

In [15]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train)


LinearRegression()

### 6. Predict

In [16]:
y_predict = model.predict(X_test_scaled)
y_predict

array([1098260.84494871, 1182461.606396  ,  928185.59581553,
       1031720.46587711,  910937.98474648, 1051648.14931924,
       1060311.1720885 ,  860448.10113195, 1373359.88419122,
       1074892.0123637 , 1164272.78208269,  681306.35683245,
        787721.36765418,  931761.01340851, 1161582.74375331,
       1008073.13043558, 1070565.48395722,  776771.77895261,
        951990.46724271, 1013721.74399457, 1054875.92849581,
        747935.13632981,  822577.52978793, 1127399.25796358,
        926158.26787387,  852736.25756325, 1045136.75698545,
        930852.36660937,  909570.03156961, 1155183.01938083,
        979157.38629658, 1153972.60218961,  889609.78168237,
        726741.20171581, 1042312.45020596, 1031878.00186276,
       1078736.63390365,  708237.3054312 , 1002526.21888159,
       1043824.63778924,  855662.26634775,  916081.4239034 ,
        833369.58250385,  994512.60492082, 1008073.13043558,
        949110.32648256, 1025668.37992105, 1057700.23527531,
       1419972.57982068,

### 7. Evaluate the model (MSE, RMSE, R²)

In [17]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

mse = mean_squared_error(y_test, y_predict)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_predict)

print("MSE:", mse)
print("RMSE:", rmse)
print("R² Score:", r2)


MSE: 7820259686.197807
RMSE: 88432.23216790249
R² Score: 0.8113758712288119


### RandomForestRegressor

In [18]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train_scaled, y_train)
y_pred= rf_model.predict(X_test)
y_pred

C:\Users\ahmed\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(


array([1429080.85430062, 1538469.23560634, 1538469.23560634,
       1538469.23560634, 1429080.85430062, 1538469.23560634,
       1538469.23560634, 1429080.85430062, 1538469.23560634,
       1538469.23560634, 1538469.23560634, 1429080.85430062,
       1538469.23560634, 1538469.23560634, 1538469.23560634,
       1538469.23560634, 1538469.23560634, 1538469.23560634,
       1538469.23560634, 1538469.23560634, 1538469.23560634,
       1429080.85430062, 1429080.85430062, 1538469.23560634,
       1425032.24633479, 1538469.23560634, 1538469.23560634,
       1538469.23560634, 1538469.23560634, 1538469.23560634,
       1538469.23560634, 1538469.23560634, 1429080.85430062,
       1538469.23560634, 1538469.23560634, 1538469.23560634,
       1538469.23560634, 1538469.23560634, 1429080.85430062,
       1538469.23560634, 1429080.85430062, 1538469.23560634,
       1538469.23560634, 1429080.85430062, 1538469.23560634,
       1538469.23560634, 1538469.23560634, 1538469.23560634,
       1538469.23560634,

In [20]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

#  Calculate MSE (Mean Squared Error)
mse = mean_squared_error(y_test, y_pred)

#  Calculate RMSE (Root Mean Squared Error)
rmse = np.sqrt(mse)

#  Calculate R² Score
r2 = r2_score(y_test, y_predict)

#  Print results
print("MSE:", mse)
print("RMSE:", rmse)
print("R² Score:", r2)


MSE: 299921994259.2869
RMSE: 547651.3437026215
R² Score: 0.8113758712288119


In [21]:
# Multiple Regression model

In [22]:
# # ==========================
# # 📦 Import Libraries
# # ==========================
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import mean_squared_error, r2_score
# from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
# from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
# from sklearn.tree import DecisionTreeRegressor
# from sklearn.neighbors import KNeighborsRegressor
# from sklearn.svm import SVR
# import numpy as np

# # ==========================
# # 🧠 Define Regression Models
# # ==========================
# models = {
#     "Linear Regression": LinearRegression(),
#     "Ridge Regression": Ridge(alpha=1.0),
#     "Lasso Regression": Lasso(alpha=0.01),
#     "ElasticNet Regression": ElasticNet(alpha=0.01, l1_ratio=0.5),
#     "Decision Tree Regressor": DecisionTreeRegressor(random_state=42),
#     "Random Forest Regressor": RandomForestRegressor(n_estimators=100, random_state=42),
#     "Gradient Boosting Regressor": GradientBoostingRegressor(random_state=42),
#     "AdaBoost Regressor": AdaBoostRegressor(random_state=42),
#     "Support Vector Regressor": SVR(kernel='rbf'),
#     "K-Nearest Neighbors Regressor": KNeighborsRegressor(n_neighbors=5)
# }

# # ==========================
# # 📈 Train, Predict, and Print Results for Each Model
# # ==========================
# for name, model in models.items():
#     print("="*70)
#     print(f"🔹 Model: {name}")
#     print(model)
#     print("-"*70)
    
#     # Train model
#     model.fit(X_train, y_train)
    
#     # Predict
#     y_pred = model.predict(X_test)
    
#     # Evaluate metrics
#     mse = mean_squared_error(y_test, y_pred)
#     rmse = np.sqrt(mse)
#     r2 = r2_score(y_test, y_pred)
    
#     # Print results
#     print(f"MSE:  {mse:.4f}")
#     print(f"RMSE: {rmse:.4f}")
#     print(f"R² Score: {r2:.4f}")



# print("✅ All models have been evaluated successfully!")
# print('model =', name, ', r2 =', r2)





### Comparing the actual price with predicted data

In [ ]:
import pandas as pd

# Create comparison DataFrame
comparison_df = pd.DataFrame({
    "Actual Price": y_test.values, #pandas series
    "Predicted Price": y_predict, #numpy
})
# errors=y_test-y_predict
# Add difference column
comparison_df["Difference(ERROR)"] = comparison_df["Actual Price"] - comparison_df["Predicted Price"]

comparison_df.head()


Actual Price  Predicted Price     Difference
0  1.088002e+06     1.098261e+06  -10258.606712
1  1.004517e+06     1.182462e+06 -177944.999900
2  8.434546e+05     9.281856e+05  -84730.974642
3  1.178394e+06     1.031720e+06  146673.036931
4  9.007468e+05     9.109380e+05  -10191.201184

#### Predicting New data(unseen data)

In [24]:
new_house = pd.DataFrame([{
    "Bedrooms": 3,
    "Bathrooms": 2,
    "HouseSize_sqft": 1500,
}])


### Scale the new data

In [25]:
new_scaled = scaler.transform(new_house)
# Step 2: Convert back to DataFrame 
new_scaled_df = pd.DataFrame(new_scaled, columns=new_house.columns)
new_scaled_df

Bedrooms  Bathrooms  HouseSize_sqft
0 -0.607066  -0.341861       -0.828113

In [26]:
prediction = model.predict(new_scaled_df)
prediction

C:\Users\ahmed\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([863574.17830352])

### Comparing Test Prediction With the Actual

In [27]:
import pandas as pd

# Create comparison DataFrame
comparison_df = pd.DataFrame({
    "Actual Price": y_test.values, #pandas series
    "Predicted Price": y_predict, #numpy
})
# errors=y_test-y_predict
# Add difference column
comparison_df["Difference"] = comparison_df["Actual Price"] - comparison_df["Predicted Price"]

comparison_df["Actual Price"] = comparison_df["Actual Price"].apply(lambda x: f"{x:,.0f}")
comparison_df["Predicted Price"] = comparison_df["Predicted Price"].apply(lambda x: f"{x:,.0f}")
comparison_df["Difference"] = comparison_df["Difference"].apply(lambda x: f"{x:,.0f}")

comparison_df.head()
# # test_data["y_predction"]=prediction
# # test_data
# # prediction

Actual Price Predicted Price Difference
0    1,088,002       1,098,261    -10,259
1    1,004,517       1,182,462   -177,945
2      843,455         928,186    -84,731
3    1,178,394       1,031,720    146,673
4      900,747         910,938    -10,191

In [28]:
import joblib
joblib.dump(model, "model.pkl")

['model.pkl']

In [29]:
joblib.dump(scaler, "scaler.pkl")


['scaler.pkl']